# Bluetooth
CONFIG_ZMK_BLE=y
CONFIG_BT_MAX_PAIRED=3
CONFIG_BT_DEVICE_NAME="KimiBoard(BT)"

# USB
CONFIG_USB_DEVICE_PRODUCT="KimiBoard(USB)"

# Trackball (PMW3610 over SPI)
CONFIG_ZMK_POINTING=y
CONFIG_ZMK_MOUSE=y
CONFIG_SPI=y
CONFIG_INPUT=y
CONFIG_INPUT_PMW3610=y
CONFIG_NFCT_PINS_AS_GPIOS=y

# RGB LED status widget
CONFIG_RGBLED_WIDGET=y
