on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    # confirmed on 2026-06-08 (branch main head); keep in sync with the zmk revision in config/west.yml
    uses: zmkfirmware/zmk/.github/workflows/build-user-config.yml@773dec58eaacaef4703b3e4595e50bd71f6cad3d
